{
 "title": "Snapshots",
 "time": { "from": "2022-09-07T09:00:22.615Z", "to": "2022-09-07T12:24:45.564Z" },
 "panels": [
  {
   "title": "Times",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "Time spent restoring",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "backup_restore_ms_sum{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Time spent storing",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "backup_store_to_backend_ms_sum{}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Total data backed up",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "backup_store_data_transferred{}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total data restored",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "backup_restore_data_transferred{}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}