{
 "title": "Usage",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Overall Object Count",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(object_count)" }
   ]
  },
  {
   "title": "Object Count per Class / Shard",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "object_count",
     "legendFormat": "{{ class_name }} / {{ shard_name }}"
    }
   ]
  },
  {
   "title": "Vector Statistics across all Classes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vector_index_operations{operation=\"create\"})",
     "legendFormat": "Vector Additions"
    },
    {
     "expr": "sum(vector_index_operations{operation=\"delete\"})",
     "legendFormat": "Vector Deletions"
    },
    {
     "expr": "sum(vector_index_operations{operation=\"create\"}) - ignoring(operation) sum(vector_index_operations{operation=\"delete\"})",
     "legendFormat": "Net Vectors"
    }
   ]
  }
 ]
}